Repository mcbookshelf/bookshelf, pull requests merged in 2023-08, with the labels that each got.

#72 Add new line normalization
  .editorconfig
  .gitattributes
Labels: Enhancement

#77 ♻️ Applied nomenclature convention to fake players
  datapacks/Bookshelf/data/bs.bitwise/functions/two_complement.mcfunction
  datapacks/Bookshelf/data/bs.core/functions/import/constants.mcfunction
  datapacks/Bookshelf/data/bs.math/functions/arctan/child/above_718.mcfunction
  datapacks/Bookshelf/data/bs.math/functions/arctan/child/below_718.mcfunction
  datapacks/Bookshelf/data/bs.math/functions/cos.mcfunction
  datapacks/Bookshelf/data/bs.math/functions/cos/accuracy/10-3.mcfunction
  datapacks/Bookshelf/data/bs.math/functions/sin/accuracy/10-3.mcfunction
  datapacks/Bookshelf/data/bs.move/functions/forward/config/collision/type_1.mcfunction
Labels: Refactor

#71 Update conventions
  docs/contribute/configuration.md
  docs/contribute/debug.md
  docs/contribute/definitions.md
  docs/contribute/file_format.md
  docs/contribute/index.md
  docs/contribute/nomenclature.md
  docs/contribute/special_scores.md
  docs/contribute/tree_structure.md
Labels: Documentation
